dataname: 'test'
path: '/home/matias/DATA/Dog-Cat-Classifier/Data/Train_Data/all'
nimages: 1500
xdim: 100
ydim: 30
tileSize: 256
minXrange: 0
minYrange: 0
#### SERVER
server:
  ssl: true
  sslName: test #prefix of .crt and .key files inside ssl/ folder e.g., ssl/{sslName.key}
  host: 'https://localhost'
  port: 8888
  #workers: None # None will default to the workers in the machine
#### CLIENT
client:
  host: 'http://localhost'
  port: 8000
#### classes
classes:
    - Elliptical: 9
    - Spiral: 8
    - Other: 7
    - Delete: 0
