dataname: 'test'
path: '/home/matias/DES/box10/images'
#path: '/home/matias/Downloads/sample/sampled_galaxies/sampled'
nimages: 900
xdim: 30
ydim: 30
tileSize: 256
#minZoom: 0
#maxZoom: 7
#tilesX: 128
#tilesY: 128
#maxXrange: 20480
#maxYrange: 5120
minXrange: 0
minYrange: 0
#widthDiv: 1280
#heightDiv: 512
#### SERVER
server:
  host: 'http://localhost'
  port: 8888
  #workers: None # None will default to the workers in the machine
#### CLIENT
client:
  port: 8000
#### classes
classes:
    - Elliptical: 9
    - Spiral: 8
    - Other: 7
    - Delete: 0
